version: "3.3"
services:
  rtmp:
    build: ./nginx-rtmp_html
    ports:
      - "1935:1935"
      - "80:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./rtmp-auth
    container_name: auth_server